### ISSUE TITLE
HttpRequest.withCredentials = true does not seem to work

### ISSUE THREAD

**Issue by Maximaximum** [souldreamer/node-angular-http-client#1]
Hi! Thanks for the great job! :)

However, it seems like setting withCredentials to true does not work. The server does not receive the cookie.

A possible way to implement this could be to do something similar to what we have in chai-http: https://github.com/visionmedia/superagent/blob/master/lib/node/agent.js

**Comment by souldreamer** [comment]
Hi! Glad you're enjoying the lib.

Unfortunately, adding cookie support isn't quite that easy. As Angular is mainly used in the browser, it's very much dependent on XHR. For Angular Universal it uses the xhr2 library to polyfill XMLHttpRequest, and it unfortunately doesn't support cookies. An actual solution to your problem would be extending the xhr2 library to support them or rewriting the polyfill.

Looking into it though and I'll let you know. Does sound like an interesting problem to solve, I'd hit it myself in the project I wrote the library for 😄  (just didn't have the time at that point to look into it as it was a last-minute spec change so I cheated by using the request library wrapped in an Observable).

**Comment by souldreamer** [comment]
Seems like rewriting xhr2 worked 😛 . Now `withCredentials: true` seems to be passing on the cookie in subsequent redirects. Can you test it in your case and tell me if/how it works?

Thanks!

**Comment by Maximaximum** [comment]
Thanks a lot for your work again!

However, it seems like node-angular-http-client now sends GET requests even when POST is needed. I've opened a corresponding issue here: https://github.com/souldreamer/xhr2-cookies/issues/1

**Comment by souldreamer** [comment]
The fix is up in version 1.1.5 of node-angular-http-client. Thanks for testing & contributing!

**Comment by Maximaximum** [comment]
Thanks to you!

However, another issue arouse: the response headers don't get parsed. Here is a pull request for that: https://github.com/souldreamer/xhr2-cookies/pull/3

**Comment by Maximaximum** [comment]
Updated to 1.1.6, but still not working

**Comment by Maximaximum** [comment]
It seems like `XmlHttpRequest` should not be the object responsible for creating and owning the cookieJar. E.g., when we send an `authentication` message to server, it returns a `set-cookie` header. Then we try to send the next 'authenticated' request, but the new `XmlHttpRequest` object now creates its own cookieJar. And it is empty, of course

**Comment by souldreamer** [comment]
My use case had been needing to remember the cookies between redirects (which is a case that *does* work). The XMLHttpRequest spec is a bit thin on what exactly withCredentials does, but now that you mention it, it does sound like the cookieJar should be static and only used for requests/responses with set `withCredentials`.

The fix should be easy enough to implement.

Update: already done. Will be released once I have some basic tests working 🤣  - just finished the test server, too.

**Comment by Maximaximum** [comment]
Oops, sorry - I've already created a pull request that might fix this issue. Please feel free to close it if you already have implemented a fix. :)

**Comment by Maximaximum** [comment]
@souldreamer do you have any estimations on when you plan to release a working version?

It would be great if you could release what you have now (even if it's not perfect or lacks tests etc)

**Comment by souldreamer** [comment]
Added now. Version `1.1.7` should do what you need. See [this test](https://github.com/souldreamer/xhr2-cookies/blob/master/test/cookies.spec.ts) for proof that `xhr2-cookies` does what it should in your case. Tests for this repository will have to wait for a bit 🤣

**Comment by Maximaximum** [comment]
Indeed, finally everything seems to be working with my use case! :tada:

Thanks a lot for your work! :)
